name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact
        reqired: false
        default: dist
        type: string
jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Cleanup artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
